CREATE TABLE movie (
    film_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(250) NOT NULL,
    description varchar(200),
    mpa varchar(7),
    release_date timestamp,
    duration integer
);

CREATE TABLE genre (
    genre_id TINYINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(100)
);

CREATE TABLE film_genre (
    genre_id TINYINT REFERENCES genre(genre_id),
    film_id BIGINT REFERENCES movie(film_id)
);

CREATE TABLE user_id (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email varchar(254) NOT NULL,
    login varchar(30) NOT NULL,
    name varchar(100),
    birthday timestamp
);

CREATE TABLE likes (
    like_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    film_id BIGINT REFERENCES movie(film_id),
    user_id BIGINT REFERENCES user_id(user_id)
);

CREATE TABLE friendship (
    friendship_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES user_id(user_id),
    friend_id BIGINT REFERENCES user_id(user_id),
    confirmation boolean
);
