CREATE TABLE IF NOT EXISTS mpa(
    mpa_id int generated by default as identity primary key,
    mpa_name varchar(6)
    );

CREATE TABLE IF NOT EXISTS film (
    film_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(250) NOT NULL,
    description varchar(200),
    release_date timestamp,
    mpa TINYINT REFERENCES mpa(mpa_id),
    duration integer
    );

CREATE TABLE IF NOT EXISTS genre (
    genre_id TINYINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(100)
    );

CREATE TABLE IF NOT EXISTS film_genre (
    genre_id TINYINT REFERENCES genre(genre_id),
    film_id BIGINT REFERENCES film(film_id)
    );

CREATE TABLE IF NOT EXISTS person (
    person_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email varchar(254) NOT NULL,
    login varchar(30) NOT NULL,
    name varchar(100),
    birthday timestamp
    );

CREATE TABLE IF NOT EXISTS likes (
    film_id BIGINT REFERENCES film(film_id),
    user_id BIGINT REFERENCES person(person_id)
    );

CREATE TABLE IF NOT EXISTS friendship (
    user_id BIGINT REFERENCES person(person_id),
    friend_id BIGINT REFERENCES person(person_id),
    confirmation boolean DEFAULT false
    );




