

CREATE TABLE IF NOT EXISTS mpa(
    id int generated by default as identity primary key,
    name varchar(6)
);

CREATE TABLE IF NOT EXISTS film (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(250) NOT NULL,
    description varchar(200),
    release_date timestamp,
    mpa TINYINT REFERENCES mpa(id),
    duration integer
);

CREATE TABLE IF NOT EXISTS genre (
    genre_id TINYINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(100)
);

CREATE TABLE IF NOT EXISTS film_genre (
    genre_id TINYINT REFERENCES genre(genre_id),
    film_id BIGINT REFERENCES film(id)
);

CREATE TABLE IF NOT EXISTS person (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email varchar(254) NOT NULL,
    login varchar(30) NOT NULL,
    name varchar(100),
    birthday timestamp
);

CREATE TABLE IF NOT EXISTS likes (
    film_id BIGINT REFERENCES film(id),
    user_id BIGINT REFERENCES person(id)
);

CREATE TABLE IF NOT EXISTS friendship (
    user_id BIGINT REFERENCES person(id),
    friend_id BIGINT REFERENCES person(id),
    confirmation boolean
);

CREATE TABLE IF NOT EXISTS mpa(
    id int PRIMARY KEY,
    name varchar(6)
);


